default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: GET